#!/usr/bin/env python3
# SMS Eagle Appliance
"""
Sms Eagle
"""
# pylint: disable=too-many-locals, import-error, broad-exception-raised, bare-except
import sys
import requests
import logging
from cmk.notification_plugins import utils
from cmk.notification_plugins.utils import get_password_from_env_or_context
from urllib3.exceptions import InsecureRequestWarning
from urllib3 import disable_warnings
disable_warnings(InsecureRequestWarning)
logging.basicConfig(level=logging.DEBUG)
logging.getLogger('urllib3').setLevel(logging.DEBUG)

class NotifyEagle():
    """
    Eagle Notification Class
    """

    def __init__(self):
        """
        Perpare Config and Params
        """
        context = utils.collect_context()
        self.config = {
            'api_host': context['PARAMETER_API_HOST'],
            'api_token': get_password_from_env_or_context(key="PARAMETER_API_TOKEN", context=context),
        }
        self.context = context

    def get_message(self):
        """
        Build SMS Text
        """

        messages = []
        messages.append(self.context['HOSTNAME'])
        if self.context['WHAT'] == 'HOST':
            messages.append(self.context['HOSTSTATE'])
            messages.append(self.context['HOSTOUTPUT'])
        else:
            messages.append(self.context['SERVICESTATE'])
            messages.append(self.context['SERVICEDESC'])
            messages.append(self.context['SERVICEOUTPUT'])

        return " ".join(messages)[:160]

    def notify(self):
        """
        Main part
        """
        url = f"{self.config['api_host']}/api/v2/messages/sms_single"
        payload = {
            'to': self.context['CONTACTPAGER'],
            'text': self.get_message(),

        }
        headers ={
            'access-token': self.config['api_token'],
            'Content-Type': 'application/json',
        }
        response = requests.data(url, json=payload, headers=headers, timeout=10)
        if response.status_code != 200:
            print(response.text, response.url)
            return 1
        print(response.text)
        return 0

if __name__ == "__main__":
    notify = NotifyEagle()
    sys.exit(notify.notify())
