#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

import shlex


def quote_shell_string(what):
    """
    Quote String
    """
    return shlex.quote(what)

def agent_unisphere_powermax_arguments(params, hostname, ipaddress):
    """
    Define the Arguements
    """
    args = ''
    args += " --user " + quote_shell_string(params["username"])
    args += " --password " + quote_shell_string(params["password"])
    args += " --port " + str(params["port"])
    args += " --disablegetSrpInfo " if params.get("disablegetSrpInfo", False) else ""
    args += " --disablegetDirectorInfo " if params.get("disablegetDirectorInfo", False) else ""
    args += " --disablegetHealthScoreInfo " if params.get("disablegetHealthScoreInfo", False) else ""
    args += " --disablegetHealthCheckInfo " if params.get("disablegetHealthCheckInfo", False) else ""
    args += " --disablegetArrayPerformanceInfo " if params.get("disablegetArrayPerformanceInfo", False) else ""
    args += " --disablegetPortGroupInfo " if params.get("disablegetPortGroupInfo", False) else ""
    args += " --disablegetAlertInfo " if params.get("disablegetAlertInfo", False) else ""
    args += " --disablegetMaskingViewInfo " if params.get("disablegetMaskingViewInfo", False) else ""
    args += " --enableRemoteSymChecks " if params.get("enableRemoteSymChecks", False) else ""
    args += " --cache-time {} ".format(str(params["cache-time"])) if params.get("cache-time", False) else ""
    args += " --noCertCheck " if params.get("no_cert_check", False) else ""
    if ipaddress is not None and params.get("useIP", False):
        args += " " + quote_shell_string(ipaddress)
    else:
        args += " " + quote_shell_string(hostname)

    return args

special_agent_info['unisphere_powermax'] = agent_unisphere_powermax_arguments

