#!/usr/bin/env python3
"""
Host Mover
"""
# pylint: disable=invalid-name, broad-except
import getopt
import sys
import os
from shutil import copytree, copyfile, rmtree

def usage():
    """
    Print Usage
    """
    sys.stdout.write("""Usage: host_mover -s SOURCE_SITE -t TARGET_SITE -H HOSTNAME

This program moves hosts in between sites.

Options:

  -v, --verbose     Verbose mode
  -s, --source      Source OMD Site
  -t, --target      Target OMD Site
  -H, --host        Hostname
  -L, --logfiles    Handle Logfiles
  -P, --perfdata    Handle Perfdata
  -A, --autochecks  Handle Autocheck files
  -I, --inventory   Handle Inventory Data
  -a, --all         Copy all Data
  -u, --uid         UID for chown
  -g, --gid         GID for chown
  -d, --debug       Output Debug Messages

""")


short_options = 'vs:t:hH:aLPu:g:Ad'
long_options = [
    'verbose', 'source=', 'target=', 'host=', 'help', 'all',
    'logfiles', 'perfdata', 'uid=', 'guid=', 'autochecks',
    'debug',
]

opt_verbose = False
opt_debug = False
opt_source = ""
opt_target = ""
opt_host = ""
opt_logfiles = False
opt_perfdata = False
opt_inventory = False
opt_omd_base = '/opt/omd/sites/'
opt_uid = 0
opt_gid = 0
opt_autochecks = False

try:
    opts, args = getopt.getopt(sys.argv[1:], short_options, long_options)
except getopt.GetoptError as err:
    sys.stderr.write("%s\n\n" % err)
    usage()
    sys.exit(1)

for o, a in opts:
    if o in ['-h', '--help']:
        usage()
        sys.exit(0)

    elif o in ['-v', '--verbose']:
        opt_verbose = True
    elif o in ['-d', '--debug']:
        opt_debug = True
    elif o in ['-s', '--source']:
        opt_source = a
    elif o in ['-t', '--target']:
        opt_target = a
    elif o in ['-H', '--host']:
        opt_host = a
    elif o in ['-a', '--all']:
        opt_logfiles = True
        opt_perfdata = True
        opt_autochecks = True
        opt_inventory = True
    elif o in ['-I', '--inventory']:
        opt_inventory = True
    elif o in ['-L', '--logfiles']:
        opt_logfiles = True
    elif o in ['-P', '--perfdata']:
        opt_perfdata = True
    elif o in ['-A', '--autochecks']:
        opt_autochecks = True
    elif o in ['-g', '--gid']:
        opt_gid = int(a)
    elif o in ['-u', '--uid']:
        opt_uid = int(a)

if not opt_host or not opt_target or not opt_source:
    usage()
    sys.exit(1)

# Helpers
def verbose(msg):
    """
    Print Verbose
    """
    if opt_verbose:
        sys.stdout.write(msg + "\n")

def debug(msg):
    """
    Debug Messages
    """
    if opt_debug:
        sys.stderr.write(msg + "\n")

source_site = opt_omd_base+opt_source+"/"
target_site = opt_omd_base+opt_target+"/"

def prepare_host_url(var_part, appendix=""):
    """
    Return Source and Target url of an object
    """
    return (
        source_site + var_part + opt_host + appendix,
        target_site + var_part + opt_host + appendix,
    )

def find_loglines(path, searchhost):
    """
    Find all to Host related lines for a host
    """
    try:
        logfiles = list(os.walk(path))[0][2]
    except IndexError:
        sys.stderr.write("Path not found or empty: {}".format(path))
    found_lines = {}
    verbose("+++Start Parsing+++")
    for logfile in logfiles:
        with open(path+logfile) as data:
            verbose("... Parse: " + path+logfile)
            for line in data.readlines():
                try:
                    splited = line.split()
                    if len(splited) <= 2:
                        continue
                    if splited[1] not in ["INITAL", "SERVICE", "HOST"]:
                        continue

                    message = line.split(":", 1)[1].strip().split(';')
                    if len(message) > 3:
                        continue
                    if splited[2].startswith('NOTIFICATION'):
                        hostname = message[0].split(':')[1].strip()
                    else:
                        hostname = message[0]

                    if searchhost != hostname:
                        continue

                    found_lines.setdefault(logfile, [])
                    found_lines[logfile].append(line)
                except Exception as error:
                    info = " -- Error Parsing line: '{}'".format(line)
                    debug(str(error)+info)
    return found_lines


def write_logfiles(path, hostname, config):
    """
    Write new logfiles
    """
    verbose("+++Start Writing+++")
    for logfile, lines in config.items():
        outfilename = logfile+'-'+hostname
        if logfile.endswith('-'+hostname):
            outfilename = logfile
        with open(path+outfilename, "w+") as outfile:
            verbose("... Write "+path+outfilename)
            for line in lines:
                outfile.write(line)

        if opt_uid and opt_gid:
            os.chown(path+outfilename, opt_uid, opt_gid)


if opt_logfiles:
    verbose("Start Logfiles for {}...".format(opt_host))
    logfile_path = 'var/check_mk/core/archive/'

    logfile_data = find_loglines(source_site+logfile_path, opt_host)
    write_logfiles(target_site+logfile_path, opt_host, logfile_data)
    verbose("...done")

if opt_perfdata:
    verbose("Start Perfdata for {}...".format(opt_host))
    try:
        perfdata_path = 'var/check_mk/rrd'
        perf_source, perf_target = prepare_host_url(perfdata_path)
        try:
            rmtree(perf_target)
        except FileNotFoundError:
            pass
        copytree(perf_source, perf_target)
        if opt_uid and opt_gid:
            verbose("... Set UID")
            os.chown(perf_target, opt_uid, opt_gid)
            for root, _dirs, files in os.walk(perf_target):
                for perf_file in files:
                    perf_file_path = os.path.join(root, perf_file)
                    os.chown(perf_file_path, opt_uid, opt_gid)
    except Exception as error:
        debug("Perfdata Problem: {}, Source: {}, Target {}".format(error, perf_source, perf_target))
    else:
        verbose("... Copied {} to {}".format(perf_source, perf_target))

copy_file_list = []

if opt_inventory:
    verbose("Prepare Inventory data for {}...".format(opt_host))
    inventory_path = 'var/check_mk/inventory/'
    source, target = prepare_host_url(inventory_path)
    copy_file_list.append((source, target))
    copy_file_list.append((source+'.gz', target+'.gz'))
    verbose("...done")

if opt_autochecks:
    verbose("Prepare Autochecks for {}...".format(opt_host))
    autochecks_path = 'var/check_mk/autochecks/'
    source, target = prepare_host_url(autochecks_path, '.mk')
    copy_file_list.append((source, target))
    verbose("...done")

if copy_file_list:
    verbose("Staring Copy Jobs for {}... ".format(opt_host))
    if opt_uid and opt_gid:
        verbose("... Set UID enabled")
    for source, target in copy_file_list:
        try:
            copyfile(source, target)
            verbose("...> Copied {} to {}".format(source, target))
            if opt_uid and opt_gid:
                os.chown(target, opt_uid, opt_gid)
        except FileNotFoundError as error:
            debug("Error: {} with {}".format(error, target))
    verbose("...done")
