#!/usr/bin/env python
#pylint: disable=undefined-variable, missing-docstring


def agent_csmon_arguments(params, hostname, ipaddress):
    args = '%s %s %s' % (hostname, params['username'], params['password'])
    return args

special_agent_info['csmon'] = agent_csmon_arguments

