#!/usr/bin/env python3

"""
Kuhn & Rueß GmbH
Consulting and Development
https://kuhn-ruess.de
"""

from json import dumps
from os import environ
from requests import get
from sys import argv

from cmk.utils.site import get_apache_port, omd_site


class AgentServicecounter():
    """
    Agent Json
    """

    def get_user(self):
        """
        Get automation user and secret
        """
        with open(f"{environ.get('OMD_ROOT')}/var/check_mk/web/automation/automation.secret", "r") as f:
            data = f.read()
            f.close()

        self._username = "automation"
        self._secret = data.strip()


    def __init__(self):
        """
        Init
        """
        self.timeout = float(argv[1])
        self.config = [ x.split("|") for x in argv[2:]]
        self.get_user()
        self._site_url = f"http://localhost:{get_apache_port()}/{omd_site()}/check_mk/api/1.0"


    def get(self, url, params):
        """
        Simple Get
        """
        content = get(
            f"{self._site_url}{url}",
            params = params,
            headers = {"Authorization": f"Bearer {self._username} {self._secret}"},
            timeout = self.timeout,
        )

        if content.status_code == 200 or content.status_code == 204:
            return content.json()
        else:
            return {}


    def get_services(self):
        """
        Get services from Livestatus API
        """
        print("<<<local>>>")
        for service_name, service_output in self.config:
            expr = []
            expr.append(
                {
                    "op": "and", "expr": [
                        {"op": "=", "left": "description", "right": f"{service_name}"},
                        {"op": "~", "left": "plugin_output", "right": f"{service_output}"}
                    ]
                }
            )

            params = {
                "query": str(
                    dumps(
                        {
                            "op": "or",
                            "expr": expr,
                        }
                    )
                )
            }

            url = "/domain-types/service/collections/all"
            count = len(self.get(url, params)['value'])
            print(f"0 \"Count {service_name} {service_output}\" count={count} Found {count} times")


if __name__ == "__main__":
    agent = AgentServicecounter()
    agent.get_services()
