#!/usr/bin/env python3
"""
Kuhn & Rueß GmbH
Consulting and Development
https://kuhn-ruess.de
"""
from sys import argv
import requests
from requests.auth import HTTPBasicAuth


class AgentSemu():
    """
    Agent SEMU
    """

    def __init__(self):
        """
        Init
        """
        self.hostname = argv[1]
        self.username = argv[2]
        self.password = argv[3]

    def get_frames(self):
        """
        Return List of Jobs
        """
        print("<<<semu_frames>>>")
        basic = HTTPBasicAuth(self.username, self.password)
        url = f'https://{self.hostname}/api/v5/singlesensor/status'
        response = requests.get(url, auth=basic)
        print(response.text)


if __name__ == "__main__":
    agent = AgentSemu()
    agent.get_frames()
