#!/usr/bin/python

def inventory_as400_jobs(info):
  return [('', None)]

def check_as400_jobs(item, params, info):

  warn,crit = params["jobs_levels"]
  jobs_num  = saveint(info[0][0])

  perfdata  = [ ( "jobs", jobs_num, warn, crit, None, None ) ]
  output    = "AS/400 Jobs at %d" % jobs_num

  rc = 0
  if jobs_num >= crit:
    rc = 2
  elif jobs_num >= warn:
    rc = 1

  return (rc, output, perfdata)

check_info["as400_jobs"] = {
    "check_function"          : check_as400_jobs,
    "inventory_function"      : inventory_as400_jobs,
    "service_description"     : "Jobs",
    "has_perfdata"            : True,
    "group"                   : "as400_jobs",
    "default_levels_variable" : "as400_jobs_defaults",
    "includes"                : ["as400.include"]
}

# OID is HOST-RESOURCES-MIB::hrSystemProcesses.0
snmp_info["as400_jobs"] = ( ".1.3.6.1.2.1.25.1.6", ["0"])

# Apply the check only if SNMP sysDescr starts with "IBM OS/400"
snmp_scan_functions['as400_jobs'] = \
    lambda oid: oid(".1.3.6.1.2.1.1.1.0").startswith("IBM OS/400")
