#!/usr/bin/python

def inventory_as400_users(info):
  return [('', None)]

def check_as400_users(item, params, info):

  warn,crit = params["users_levels"]
  users_num  = saveint(info[0][0])

  perfdata  = [ ( "users", users_num, warn, crit, None, None ) ]

  if (users_num == 1):
    output = "%d logged in user" % users_num
  else:
    output = "%d logged in users" % users_num

  rc = 0
  if users_num >= crit:
    rc = 2
  elif users_num >= warn:
    rc = 1

  return (rc, output, perfdata)

check_info["as400_users"] = {
    "check_function"          : check_as400_users,
    "inventory_function"      : inventory_as400_users,
    "service_description"     : "Users",
    "has_perfdata"            : True,
    "group"                   : "as400_users",
    "default_levels_variable" : "as400_users_defaults",
    "includes"                : ["as400.include"]
}

# OID is HOST-RESOURCES-MIB::hrSystemNumUsers.0
snmp_info["as400_users"] = ( ".1.3.6.1.2.1.25.1.5", ["0"])

# Apply the check only if SNMP sysDescr starts with "IBM OS/400"
snmp_scan_functions['as400_users'] = \
    lambda oid: oid(".1.3.6.1.2.1.1.1.0").startswith("IBM OS/400")
