#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# https://mibs.observium.org/mib/A10-AX-MIB/


def inventory_a10_loadbalancer_power(info):
    for line in info:
        if line[1] == '1':
            yield line[0], {}

def check_a10_loadbalancer_power(item, _params, info):
    states = {
        '0' : 'off',
        '1' : 'on',
        '2' : 'absent',
        '-1' : 'unknown',
    }
    for line in info:
        supply_state = line[1]
        if line[0] == item:
            if supply_state == '1':
                state = 0
            elif supply_state == '2':
                state = 2
            elif supply_state in ['0', '-1']:
                state = 1
            return state, "State: {}".format(states[supply_state])

check_info["a10_loadbalancer_power"] = {
    "inventory_function": inventory_a10_loadbalancer_power,
    "check_function": check_a10_loadbalancer_power,
    "service_description": "Power Supply %s",
    "has_perfdata": False,
    "snmp_scan_function": lambda oid: oid('.1.3.6.1.2.1.1.2.0') in [
        ".1.3.6.1.4.1.22610.1.3.22",
    ],
    "snmp_info": (".1.3.6.1.4.1.22610.2.4.1.5.12.1", [
        "2", #axPowerSupplyName
        "3", #axPowerSupplyStatus
    ]),
}
