#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# https://mibs.observium.org/mib/A10-AX-MIB/


def inventory_a10_loadbalancer_temp(info):
    return [('System', {})]

def check_a10_loadbalancer_temp(item, params, info):
    temp = int(info[0][0])
    return check_temperature(temp, params, "a10_loadbalancer_temp_%s" % item)


check_info["a10_loadbalancer_temp"] = {
    "inventory_function": inventory_a10_loadbalancer_temp,
    "check_function": check_a10_loadbalancer_temp,
    'service_description': 'Temperature %s',
    "has_perfdata": True,
    "snmp_scan_function": lambda oid: oid('.1.3.6.1.2.1.1.2.0') in [
        ".1.3.6.1.4.1.22610.1.3.22",
    ],
    "snmp_info": (".1.3.6.1.4.1.22610.2.4.1.5", [
        "1", #AxSyshwPhySystemTemp
    ]),
    "group": "temperature",
    "includes": ["temperature.include"],
}
