#!/usr/bin/env python3
"""
Checkmk Special Agent for Icinga
"""
import argparse

import requests
from requests.auth import HTTPBasicAuth

from urllib3.exceptions import InsecureRequestWarning
from urllib3 import disable_warnings


ssl_verify = False

if not ssl_verify:
    disable_warnings(InsecureRequestWarning)


parser = argparse.ArgumentParser(description="Icinga Special Agent")
parser.add_argument("--hostname")
parser.add_argument("--username")
parser.add_argument("--password")

args = parser.parse_args()

hostname = args.hostname
username = args.username
password = args.password

auth = HTTPBasicAuth(username, password)

print("<<<check_mk>>>\nVersion: 1.0.0\nAgentOS: icinga  connector\n")

# Get All Services
url = f"https://{hostname}/v1/objects/services"
response = requests.get(url, auth=auth, timeout=30, verify=ssl_verify)

for result_set in response.json()['results']:
    attrs = result_set['attrs']
    print(f"<<<<{attrs['host_name']}>>>")
    print("<<<local>>>")
    output = attrs['last_check_result']['output']
    perfdata =attrs['last_check_result']['performance_data']
    print(f"{attrs['state']} {attrs['name']} {perfdata} {output}")

print("<<<<>>>>")