#!/usr/bin/env python3
"""
Checkmk Special Agent for CSMON
"""
import requests
import sys
from requests.auth import HTTPBasicAuth

from urllib3.exceptions import InsecureRequestWarning
from urllib3 import disable_warnings
disable_warnings(InsecureRequestWarning)

hostname = sys.argv[1]
username = sys.argv[2]
password = sys.argv[3]

auth = HTTPBasicAuth(username, password)

service_state_map = {
    'OK': 0,
    'WARNING': 1,
    'CRITICAL': 2,
    'UNKOWN': 3,
}


host_state_map = {
    'UP':  0,
    'DOWN': 2,
}

print("<<<check_mk>>>\nVersion: 1.0.0\nAgentOS: csmon connector\n")


perf_replacer = [
    ' ', '\\\\', '\\',
]


# Get All Services
url = f"https://{hostname}/api/monitoring/services?sort_by=name&sort_dir=asc&page=0&size=50000"
response = requests.get(url, auth=auth, timeout=30, verify=False)
last_host = ""
for line in response.json()['items']:
    service_state = service_state_map.get(line['current_state'],2)
    service_name = line['service_name']
    service_output = line['output'].replace('\\','\\n')
    perf_data = line['performance_data']
    hostname = line['host']['hostname']
    host_state = host_state_map.get(line['host']['current_state'],1)
    host_description = line['host']['description']
    host_address = line['host']['address']

    if last_host != hostname:
        last_host = hostname
        print(f"<<<<{hostname}>>>>")
        print("<<<local>>>")
        print(f"{host_state} 'Host State' - {host_description}, Address: {host_address}")
    service_perf = []
    for key, value in perf_data.items():
        for repl in perf_replacer:
            key = key.replace(repl, '_')
        service_perf.append(f"{key}={value['current']};"\
                            f"{value['warning']};{value['critical']};{value['min']};{value['max']}")

    perf_string = "-"
    if service_perf:
        perf_string = "|".join(service_perf)

    print(f"{service_state} '{service_name}' {perf_string} {service_output}")

print("<<<<>>>>")
