#!/usr/bin/env python3
"""
Kuhn & Rueß GmbH
Consulting and Development
https://kuhn-ruess.de

Field Names:
('ORDINAL_POSITION', <class 'int'>, None, 10, 10, 0, True)
('JOB_NAME', <class 'str'>, None, 28, 28, 0, True)
('JOB_NAME_SHORT', <class 'str'>, None, 10, 10, 0, True)
('JOB_USER', <class 'str'>, None, 10, 10, 0, True)
('JOB_NUMBER', <class 'str'>, None, 6, 6, 0, True)
('INTERNAL_JOB_ID', <class 'bytearray'>, None, 16, 16, 0, True)
('SUBSYSTEM', <class 'str'>, None, 10, 10, 0, True)
('SUBSYSTEM_LIBRARY_NAME', <class 'str'>, None, 10, 10, 0, True)
('AUTHORIZATION_NAME', <class 'str'>, None, 10, 10, 0, True)
('JOB_TYPE', <class 'str'>, None, 3, 3, 0, True)
('FUNCTION_TYPE', <class 'str'>, None, 3, 3, 0, True)
('FUNCTION', <class 'str'>, None, 10, 10, 0, True)
('JOB_STATUS', <class 'str'>, None, 4, 4, 0, True)
('MEMORY_POOL', <class 'str'>, None, 9, 9, 0, True)
('RUN_PRIORITY', <class 'int'>, None, 10, 10, 0, True)
('THREAD_COUNT', <class 'int'>, None, 10, 10, 0, True)
('TEMPORARY_STORAGE', <class 'int'>, None, 10, 10, 0, True)
('CPU_TIME', <class 'decimal.Decimal'>, None, 20, 20, 0, True)
('TOTAL_DISK_IO_COUNT', <class 'decimal.Decimal'>, None, 20, 20, 0, True)
('ELAPSED_INTERACTION_COUNT', <class 'int'>, None, 10, 10, 0, True)
('ELAPSED_TOTAL_RESPONSE_TIME', <class 'int'>, None, 10, 10, 0, True)
('ELAPSED_TOTAL_DISK_IO_COUNT', <class 'decimal.Decimal'>, None, 20, 20, 0, True)
('ELAPSED_ASYNC_DISK_IO_COUNT', <class 'decimal.Decimal'>, None, 20, 20, 0, True)
('ELAPSED_SYNC_DISK_IO_COUNT', <class 'decimal.Decimal'>, None, 20, 20, 0, True)
('ELAPSED_CPU_PERCENTAGE', <class 'decimal.Decimal'>, None, 10, 10, 2, True)
('ELAPSED_CPU_TIME', <class 'decimal.Decimal'>, None, 20, 20, 0, True)
('ELAPSED_PAGE_FAULT_COUNT', <class 'decimal.Decimal'>, None, 20, 20, 0, True)
('JOB_END_REASON', <class 'str'>, None, 60, 60, 0, True)
('SERVER_TYPE', <class 'str'>, None, 30, 30, 0, True)
('ELAPSED_TIME', <class 'decimal.Decimal'>, None, 20, 20, 3, True)
('JOB_DESCRIPTION_LIBRARY', <class 'str'>, None, 10, 10, 0, True)
('JOB_DESCRIPTION', <class 'str'>, None, 10, 10, 0, True)
('JOB_QUEUE_LIBRARY', <class 'str'>, None, 10, 10, 0, True)
('JOB_QUEUE', <class 'str'>, None, 10, 10, 0, True)
('OUTPUT_QUEUE_LIBRARY', <class 'str'>, None, 10, 10, 0, True)
('OUTPUT_QUEUE', <class 'str'>, None, 10, 10, 0, True)
('WORKLOAD_GROUP', <class 'str'>, None, 10, 10, 0, True)
('CCSID', <class 'int'>, None, 10, 10, 0, True)
('DEFAULT_CCSID', <class 'int'>, None, 10, 10, 0, True)
('SORT_SEQUENCE_LIBRARY', <class 'str'>, None, 10, 10, 0, True)
('SORT_SEQUENCE', <class 'str'>, None, 10, 10, 0, True)
('LANGUAGE_ID', <class 'str'>, None, 3, 3, 0, True)
('DATE_FORMAT', <class 'str'>, None, 4, 4, 0, True)
('DATE_SEPARATOR', <class 'str'>, None, 1, 1, 0, True)
('TIME_SEPARATOR', <class 'str'>, None, 1, 1, 0, True)
('DECIMAL_FORMAT', <class 'str'>, None, 6, 6, 0, True)
('TIMEZONE_DESCRIPTION', <class 'str'>, None, 10, 10, 0, True)
('TIMEZONE_CURRENT_OFFSET', <class 'int'>, None, 10, 10, 0, True)
('TIMEZONE_FULL_NAME', <class 'str'>, None, 50, 50, 0, True)
('TIMEZONE_ABBREVIATED_NAME', <class 'str'>, None, 10, 10, 0, True)
('JOB_TYPE_ENHANCED', <class 'str'>, None, 28, 28, 0, True)
('JOB_ENTERED_SYSTEM_TIME', <class 'datetime.datetime'>, None, 19, 19, 0, True)
('JOB_ACTIVE_TIME', <class 'datetime.datetime'>, None, 19, 19, 0, True)
('CLIENT_IP_ADDRESS', <class 'str'>, None, 45, 45, 0, True)
('JOB_USER_IDENTITY_SETTING', <class 'str'>, None, 11, 11, 0, True)
('JOB_USER_IDENTITY', <class 'str'>, None, 10, 10, 0, True)
('DBCS_CAPABLE', <class 'str'>, None, 3, 3, 0, True)
('SIGNAL_STATUS', <class 'str'>, None, 3, 3, 0, True)
('MESSAGE_REPLY', <class 'str'>, None, 3, 3, 0, True)
('END_STATUS', <class 'str'>, None, 3, 3, 0, True)
('CANCEL_KEY', <class 'str'>, None, 3, 3, 0, True)
('EXIT_KEY', <class 'str'>, None, 3, 3, 0, True)
('MAXIMUM_ACTIVE_THREADS', <class 'int'>, None, 10, 10, 0, True)
('SYSTEM_POOL_ID', <class 'int'>, None, 10, 10, 0, True)
('POOL_NAME', <class 'str'>, None, 10, 10, 0, True)
('QTEMP_SIZE', <class 'int'>, None, 10, 10, 0, True)
('PEAK_TEMPORARY_STORAGE', <class 'int'>, None, 10, 10, 0, True)
('DEFAULT_WAIT', <class 'int'>, None, 10, 10, 0, True)
('MAXIMUM_PROCESSING_TIME_ALLOWED', <class 'int'>, None, 10, 10, 0, True)
('MAXIMUM_TEMPORARY_STORAGE_ALLOWED', <class 'int'>, None, 10, 10, 0, True)
('TIME_SLICE', <class 'int'>, None, 10, 10, 0, True)
('PAGE_FAULTS', <class 'int'>, None, 20, 20, 0, True)
('TOTAL_RESPONSE_TIME', <class 'int'>, None, 20, 20, 0, True)
('INTERACTIVE_TRANSACTIONS', <class 'int'>, None, 10, 10, 0, True)
('DATABASE_LOCK_WAITS', <class 'int'>, None, 10, 10, 0, True)
('NON_DATABASE_LOCK_WAITS', <class 'int'>, None, 10, 10, 0, True)
('INTERNAL_MACHINE_LOCK_WAITS', <class 'int'>, None, 10, 10, 0, True)
('DATABASE_LOCK_WAIT_TIME', <class 'int'>, None, 10, 10, 0, True)
('NON_DATABASE_LOCK_WAIT_TIME', <class 'int'>, None, 10, 10, 0, True)
('INTERNAL_MACHINE_LOCK_WAIT_TIME', <class 'int'>, None, 10, 10, 0, True)
('SQL_STATEMENT_TEXT', <class 'str'>, None, 10000, 10000, 0, True)
('SQL_STATEMENT_STATUS', <class 'str'>, None, 8, 8, 0, True)
('SQL_STATEMENT_START_TIMESTAMP', <class 'datetime.datetime'>, None, 26, 26, 6, True)
('SQL_STATEMENT_NAME', <class 'str'>, None, 128, 128, 0, True)
('SQL_STATEMENT_LIBRARY_NAME', <class 'str'>, None, 10, 10, 0, True)
('SQL_STATEMENT_OBJECT_NAME', <class 'str'>, None, 10, 10, 0, True)
('SQL_STATEMENT_OBJECT_TYPE', <class 'str'>, None, 7, 7, 0, True)
('QUERY_OPTIONS_LIBRARY_NAME', <class 'str'>, None, 10, 10, 0, True)
('SQL_ACTIVATION_GROUP_COUNT', <class 'int'>, None, 10, 10, 0, True)
('SQL_DESCRIPTOR_COUNT', <class 'int'>, None, 20, 20, 0, True)
('SQL_LOB_LOCATOR_COUNT', <class 'int'>, None, 10, 10, 0, True)
('CLI_HANDLE_COUNT', <class 'int'>, None, 20, 20, 0, True)
('SQL_SERVER_MODE', <class 'str'>, None, 3, 3, 0, True)
('CLIENT_ACCTNG', <class 'str'>, None, 255, 255, 0, True)
('CLIENT_APPLNAME', <class 'str'>, None, 255, 255, 0, True)
('CLIENT_PROGRAMID', <class 'str'>, None, 255, 255, 0, True)
('CLIENT_USERID', <class 'str'>, None, 255, 255, 0, True)
('CLIENT_WRKSTNNAME', <class 'str'>, None, 255, 255, 0, True)
('ROUTINE_TYPE', <class 'str'>, None, 1, 1, 0, True)
('ROUTINE_SCHEMA', <class 'str'>, None, 128, 128, 0, True)
('ROUTINE_SPECIFIC_NAME', <class 'str'>, None, 128, 128, 0, True)
('CLIENT_PORT', <class 'int'>, None, 10, 10, 0, True)
('CLIENT_HOST', <class 'str'>, None, 255, 255, 0, True)
('INTERFACE_NAME', <class 'str'>, None, 127, 127, 0, True)
('INTERFACE_TYPE', <class 'str'>, None, 63, 63, 0, True)
('INTERFACE_LEVEL', <class 'str'>, None, 63, 63, 0, True)
('SERVER_MODE_CONNECTING_JOB', <class 'str'>, None, 28, 28, 0, True)
('SERVER_MODE_CONNECTING_THREAD', <class 'int'>, None, 20, 20, 0, True)
('PRESTART_JOB_REUSE_COUNT', <class 'int'>, None, 10, 10, 0, True)
('PRESTART_JOB_MAX_USE_COUNT', <class 'int'>, None, 10, 10, 0, True)
('AVAILABLE_RESULT_SETS', <class 'int'>, None, 10, 10, 0, True)
('UNCONSUMED_RESULT_SETS', <class 'int'>, None, 10, 10, 0, True)
('OPEN_CURSOR_COUNT', <class 'int'>, None, 10, 10, 0, True)
('FULL_OPEN_CURSOR_COUNT', <class 'int'>, None, 20, 20, 0, True)
('PSEUDO_OPEN_CURSOR_COUNT', <class 'int'>, None, 20, 20, 0, True)
('PSEUDO_CLOSED_CURSOR_COUNT', <class 'int'>, None, 10, 10, 0, True)
('CQE_CURSOR_COUNT', <class 'int'>, None, 10, 10, 0, True)
('CQE_CURSOR_STORAGE', <class 'int'>, None, 10, 10, 0, True)
('SQE_CURSOR_COUNT', <class 'int'>, None, 10, 10, 0, True)
('SQE_CURSOR_STORAGE', <class 'int'>, None, 10, 10, 0, True)
('LARGEST_QUERY_SIZE', <class 'int'>, None, 10, 10, 0, True)
('QRO_HASH', <class 'str'>, None, 8, 8, 0, True)
('OPEN_FILES', <class 'int'>, None, 10, 10, 0, True)
"""
from sys import argv
import pyodbc


class AgentAs400():
    """
    Agent AS400
    """

    def __init__(self):
        """
        Init
        """
        driver = argv[1]
        system = argv[2]
        uid = argv[3]
        pwd = argv[4]

        self.connection = pyodbc.connect(
           driver=driver,
           system=system,
           uid=uid,
           pwd=pwd)

    def get_jobs(self):
        """
        Return List of Jobs
        """
        query = 'SELECT * FROM TABLE(QSYS2.ACTIVE_JOB_INFO())'
        c1 = self.connection.cursor()
        c1.execute(query)

        print("<<<as400_agent_jobs>>>")
        
        # Extrahiere nur die Spaltennamen aus der Beschreibung
        field_names = [description[0] for description in c1.description]
        for row in c1:
            job_dict = dict(zip(field_names, row))
            print(f"[[[{job_dict['JOB_NAME']}]]]")
            for key, value in job_dict.items():
                print(f"{key} {value}")
   

if __name__ == "__main__":
    agent = AgentAs400()
    agent.get_jobs()
