#!/usr/bin/env python3

"""
Kuhn & Rueß GmbH
Consulting and Development
https://kuhn-ruess.de
"""

import json
import argparse
import requests
#from requests.auth import HTTPBasicAuth


class CMDBSYncer():
    """
    CMDB Syncer
    """

    volume_names_map = {}

    def __init__(self, api_host, username, password, timeout):
        """
        Init
        """
        self.api_host = api_host
        #self.auth = HTTPBasicAuth(user, password)
        self.username = username
        self.password = password
        self.timeout = float(timeout)

    def request(self, what):
        """
        Request Data
        """
        headers = {
            'x-login-user': f"{self.username}:{self.password}",
        }
        url = f'{self.api_host}/api/v1/{what}'
        response = requests.get(url, headers=headers, timeout=self.timeout)
        try:
            return response.json()['result']
        except (KeyError, TypeError):
            if response.status_code == 401:
                return {'name': "invalid_login", "message": "Please check login", "has_error": True}
            return {'name': 'not_found', "message": "Object not Found", "has_error": True}

    def get_service(self, service_name):
        """
        Get Latest Service Log Entry
        """
        print(f"[[[{service_name}]]]")
        response = self.request(f'syncer/services/{service_name}')
        print(json.dumps(response))

    def get_cron(self):
        """
        Get Latest Service Log Entry
        """
        print(json.dumps(self.request('syncer/cron/')))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="CMDBSyncer Special Agent")
    parser.add_argument("--api_url")
    parser.add_argument("--username")
    parser.add_argument("--password")
    parser.add_argument("--timeout")
    parser.add_argument("--services")
    parser.add_argument("--fetch_cron")

    args = parser.parse_args()

    syncer = CMDBSYncer(args.api_url, args.username, args.password, args.timeout)

    if args.services:
        print("<<<cmdb_syncer_service:sep(0)>>>")
        for service in args.services.split(';'):
            syncer.get_service(service)
    if args.fetch_cron:
        print("<<<cmdb_syncer_cron:sep(0)>>>")
        syncer.get_cron()
