#!/usr/bin/env python3

"""
Kuhn & Rueß GmbH
Consulting and Development
https://kuhn-ruess.de
"""

import json
import argparse
import requests
#from requests.auth import HTTPBasicAuth


class CMDBSYncer():
    """
    CMDB Syncer
    """

    volume_names_map = {}

    def __init__(self, api_host, password, timeout):
        """
        Init
        """
        self.api_host = api_host
        #self.auth = HTTPBasicAuth(user, password)
        self.password = password
        self.timeout = float(timeout)

    def request(self, what):
        """
        Request Data
        """
        headers = {
            'x-login-token': self.password,
        }
        url = f'{self.api_host}/api/v1/{what}'
        response = requests.get(url, headers=headers, timeout=self.timeout)
        try:
            return response.json()['result']
        except KeyError:
            return {'error', 'not_found'}

    def get_service(self, service_name):
        """
        Get Latest Service Log Entry
        """
        print(f"[[[{service_name}]]]")
        print(json.dumps(self.request(f'syncer/services/{service_name}')))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="CMDBSyncer Special Agent")
    parser.add_argument("--api_url")
    parser.add_argument("--password")
    parser.add_argument("--timeout")
    parser.add_argument("--services")

    args = parser.parse_args()

    syncer = CMDBSYncer(args.api_url, args.password, args.timeout)

    print("<<<cmdb_syncer_service:sep(0)>>>")
    for service in args.services.split(';'):
        syncer.get_service(service)
