#!/usr/bin/env python

factory_settings['postgres_replication_default_levels'] = {
    'levels' : (31457280, 62914560)
}

def inventory_postgres_replication(info):
    for line in info:
        yield line[0], {}

def check_postgres_replication(item, params, info):
    for line in info:
        slot_name, slot_type, slot_lsn, delta, active,  delta_pretty, unit = line
        if slot_name == item:
            yield 0, "Slot Type: " + slot_type
            yield 0, "LSN " + slot_lsn
            if active != 't':
                yield 2, "Status inactive"
            if unit == 'bytes':
                yield check_levels(
                    int(delta_pretty),
                    'bytes',
                    params['levels'],
                    unit='Bytes',
                    infoname="Usage",
                )

check_info['postgres_replication'] = {
  'inventory_function': inventory_postgres_replication,
  'check_function' : check_postgres_replication,
  'service_description': "PostgreSQL Replication %s",
  'default_levels_variable' : 'postgres_replication_default_levels',
  'group' : 'postgres_replication',
  'has_perfdata' : True,
}
